Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
AllowedHosts: "*"
Telegram: 
  Contacts:
    Contact1:
      Name: "Contact name"
      BotToken: "YOUR_BOT_TOKEN"
      ChatId: "YOUR_CHAT_ID"
Grafana:
  Url: "GRAFANA_URL"
  Token: "YOUR_TOKEN"
  ImageWidth: 800
  ImageHeight: 400
  RejectNoData: false
  #leave blank if no redirect is needed
  RedirectNoDataToContact: "Contact name" 
