name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/Grafana.Alert.Sender.sln

    - name: Build
      run: dotnet build src/Grafana.Alert.Sender.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish src/Grafana.Alert.Sender.sln --configuration Release --no-build --output ./app

    - name: Log in Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_USERPASS }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/grafana.alert.sender:1.${{ github.run_number }} -t ${{ secrets.DOCKER_USERNAME }}/grafana.alert.sender:latest -f docker/Dockerfile .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/grafana.alert.sender:1.${{ github.run_number }}
        docker push ${{ secrets.DOCKER_USERNAME }}/grafana.alert.sender:latest
